name: 'Deploy Org Mode site to Remote'
description: 'Build and deploy a Org Mode site to a remote repository.'
author: 'lujok'
branding:
  icon: 'send'
  color: 'blue'
inputs:
  token:
    description: "Set a personal access token for pushing to the remote branch."
    required: false
    default: '${{ GITHUB_TOKEN }}'
  remote:
    description: "Set an remote repository (owner/repo)."
    required: false
    defalt: '${{ GITHUB_REPOSITORY }}'
  dest:
    description: "Set publish dictiory."
    required: false
    defalt: 'public'
  branch:
    description: "The branch of your remote repository to deploy to. Defaults to 'master'"
    required: false
  commit_message:
    description: "Custom message for remote repository's build commit."
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
